### ISSUE TITLE
Exercise switching from /usr/bin to /bin

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/shell-genomics#10]
The exercise in `01_the_filesystem.html` that starts with 

> List all of the files in /bin that start with the letter 'c

asks the learner to use the `/bin` folder, while just before the `/usr/bin` folder was used. At the Oslo workshop learners failed to notice. This didn't matter for the exercise (they still got the answers right) but maybe sticking to `/usr/bin` is better?

**Comment by smcclatchy** [comment]
This is now in episode 3, Working with Files.

**Comment by ErinBecker** [comment]
Thanks for this @lexnederbragt. It looks like this was fixed somewhere along the line in the past year. All of the references to "/bin" in 03-working-with-files.md are to "/usr/bin". Closing.
