### ISSUE TITLE
Missing newline at end of SraRunTable.txt

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/shell-genomics#11]
On the current Amazon ami, the file '/home/dcuser/dc_sample_data/sra_metadata/SraRunTable.txt' is missing a newline at the end. This results in `wc -l`counting 37 lines instead of 38

**Comment by ErinBecker** [comment]
@lexnederbragt - Thanks for noticing this. I'd like to fix this but don't know where the raw data files are and how to update them. @tracykteal could you please offer some guidance here?

**Comment by ErinBecker** [comment]
@tracykteal I missed this when we were updating the AMI. Is this a change we can still get in place before the lesson release?

**Comment by ErinBecker** [comment]
Actually, looking back at the lesson, we don't do `wc -l` on the metadata table anymore, so I'll close this.
