### ISSUE TITLE
Link check

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#111]
An automated check of all links on the site brought up this (single) error:
```
error Line: 14 http://www.datacarpentry.org/favicon-dc.ico
    Status: 404 Not Found

    The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link. 
```

It should be set to the repo's own favicon-dc.ico to work correctly. But I can not find in which file this link is actually encoded.

**Comment by ErinBecker** [comment]
@tracykteal @rgaiacs Do either of you know what this link is supposed to be pointing to?

**Comment by aschuerch** [comment]
I did this check again. The only broken link reported is the instructor guide reported in #199. I will close this issue as duplicate
