### ISSUE TITLE
need reference/glossary

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#114]

**Comment by orchid00** [comment]
yup I wanted to add to this, https://datacarpentry.org/shell-genomics/reference/ I think it is not rendering the way it should, and links seem to be broken

**Comment by ErinBecker** [comment]
https://datacarpentry.org/shell-genomics/reference/ is now rendering properly, but Glossary section is a "FIXME"

**Comment by aschuerch** [comment]
Closed with #218
