### ISSUE TITLE
Typo in Key points in 03-working-with-files

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#125]
Should say:
You can view file permissions using ls -l and change permissions using chmod. 
Instead of: 
You can view file permissions using ls -a and change permissions using chmod.

**Comment by bluegenes** [comment]
seems to be fixed already -- issue can be closed!

**Comment by ErinBecker** [comment]
Thanks @bluegenes. @ctb put in a PR that fixed this a while back but it just got merged now.
