### ISSUE TITLE
Confusing solution to challenge question in episode 3

### ISSUE THREAD

**Issue by minisciencegirl** [datacarpentry/shell-genomics#128]
In episdoe 3 (Working with files and directories), the solution to the challenge exercise where you print out the contents of the ~/dc_sample_data/untrimmed_fastq/SPR097977.fastq file does not make sense. Currently, the solution is the sequence TATTTTAAAATGGAATACCTAACATGTTAATTAACC. 

However, if it's a fastq file, shouldn't the last line be the sequence quality encoding and not the actual sequence?

**Comment by gedankenstuecke** [comment]
You are right, it's the wrong solution. #124 solved this 🙂
