### ISSUE TITLE
Redirection lesson-head command for looking at the header of the file

### ISSUE THREAD

**Issue by donalbonny** [datacarpentry/shell-genomics#129]
We can use head command with a -n  flag to look at just the first row of the file.

We can mention to the learner that: In fact, the letter n does not even need to be used at all. Just the hyphen and the integer (with no intervening space) are sufficient to tell head how many lines to return. 

---

**Comment by gedankenstuecke** [comment]
I personally would recommend to just keep the `-n` to not introduce too many concepts at once. Especially as `head` and `tail` behave differently when it comes to globbing files (at least on Linux, on MacOS the GNU versions behave differently). See examples for this below.

For `head`:

```
$ head -1 *.fasta
==> maker2pilon.all.maker.augustus_masked.proteins.fasta <==
>augustus_masked-scaffold34_size17482_pilon-abinit-gene-0.0-mRNA-1 protein AED:0.12 eAED:0.12 QI:0|1|0.66|1|1|1|3|0|150

==> maker2pilon.all.maker.augustus_masked.transcripts.fasta <==
>augustus_masked-scaffold34_size17482_pilon-abinit-gene-0.0-mRNA-1 transcript offset:0 AED:0.12 eAED:0.12 QI:0|1|0.66|1|1|1|3|0|150
```

For `tail`:

```
$ tail -1 *.fasta
tail: option used in invalid context -- 1
```

but 

```
tail -n 1 *.fasta
==> maker2pilon.all.maker.augustus_masked.proteins.fasta <==
ADIAIINLKTPIYDNMLVKVYLRALKEEPYSSIIF

==> maker2pilon.all.maker.augustus_masked.transcripts.fasta <==
TACCTGAGAGCATTGAAAGAAGAGCCCTATAGCTCTATTATTTTTTGA
```

**Comment by aschuerch** [comment]
Thank you @donalbonny for your contribution! Depending on the level of the learners at a workshop, it might indeed be a good idea to mention this. However I second the thoughts of @gedankenstuecke and would rather leave this to the freedom of the instructor and not introducing it into the lesson material. I will close this issue with that, feel free to re-open if you feel necessary.
