### ISSUE TITLE
Add instructor notes document for this lesson

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#13]
I'm working on helping direct instructor attention towards fixing up/contributing to instructor notes. Currently don't have a link to provide for instructor notes for this lesson. Please add - even a blank document would be somewhere to point towards.

**Comment by smcclatchy** [comment]
There's a page now for instructor notes, but it's blank. I'll put this on the docket for the Issue Bonanza.

**Comment by ErinBecker** [comment]
Thanks @smcclatchy

**Comment by ErinBecker** [comment]
As a reminder for whoever is putting together instructor notes, we now have a [template](https://github.com/swcarpentry/lesson-example/blob/gh-pages/_extras/guide.md).
