### ISSUE TITLE
Alphabetical summary of commands/shortcuts as downloadable PDF

### ISSUE THREAD

**Issue by Schmops78** [datacarpentry/shell-genomics#130]
Would it be possible to create an alphabetical list of all the commands and shortcuts (+ explanation and short example) used in the shell-genomics course and put them as downloadable PDF link at the very bottom of the Shell Genomics page? On such a PDF, we could separate general bash commands and shortcuts from e.g. shortcuts used in the text editor "nano". This PDF could be downloaded by the students prior to the course for practicing purposes and/or during the course as a one-page handout.

**Comment by aschuerch** [comment]
Thank you for your contribution @Schmops78! Have you already had a look at the all-in-one page  http://www.datacarpentry.org/shell-genomics/aio/? Would a pdf handout of the all-in-one page meet what you had in mind?

**Comment by Schmops78** [comment]
Yes, I like the all-in-one page. But I was more thinking about a very short summary/glossary of only the commands/shortcuts that will be used in the lesson. Without the full explanatory text/examples. Almost like a “cheat sheet” of commands/shortcuts. It would be something like:

General bash commands:

Cd = change directory
Mkdir = create a directory
Ls = List files in the current directory
Etc.

General Shortcuts:
ctrl+C = cancel command
Ctrl+l = clear screen
Etc.

This way the students would have all commands alphabetically in front of them while listening/working on the tasks during the lesson.

**Comment by aschuerch** [comment]
Like the [glossary for the SW shell-novice](http://swcarpentry.github.io/shell-novice/reference.html) but then for this lesson? This indeed still needs to be fixed (in the file reference.md). We welcome a contribution, for example in the form of a pull request.

**Comment by Schmops78** [comment]
Yes, like the glossary but more tailored to the specific lesson. Thanks Anita. I discussed this today with a trainer on zoom also. I will follow your advice and create a pull request for this. Maybe it gets integrated if approved. Thanks!

**Comment by jessicamizzi** [comment]
@Schmops78 are you still working on this glossary? If not, I can work on this effort. :)

**Comment by tracykteal** [comment]
Thanks for this idea and discussion. What about linking to a shell cheat sheet? It won't have just the commands in the lesson, but will be a good reference after the workshop too, including a few future-useful commands too. This is one example of a cheat sheet that I like. https://fosswire.com/post/2007/08/unixlinux-command-cheat-sheet/

**Comment by Schmops78** [comment]
Sure, no problem Jessica!

Sascha

**Comment by tracykteal** [comment]
OK, great, we'll add in some links. These were other suggestions. 

https://www.cheatography.com/tag/bash/
http://swcarpentry.github.io/shell-novice/reference/

**Comment by aschuerch** [comment]
see #218. Feel free to re-open if this wasn't what you had in mind
