### ISSUE TITLE
"FIXME" links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by samnooij** [datacarpentry/shell-genomics#131]
The file [CONTRIBUTING.md](https://github.com/datacarpentry/shell-genomics/blob/gh-pages/CONTRIBUTING.md) contains 7 links with "FIXME" in them. These apparently need to be fixed by the maintainer, which has not yet been done. (The last update seems to be from June 2017. It is now January 2017.) Especially the part of "Where to Contribute" is a bit confusing if the links send you to a 404 page.

**Comment by aschuerch** [comment]
Hi @samnooij, thanks for picking this up!

**Comment by jessicamizzi** [comment]
I'm working on this issue!

**Comment by ErinBecker** [comment]
Thanks @jessicamizzi!
