### ISSUE TITLE
Introduce FASTQ format earlier

### ISSUE THREAD

**Issue by jrkirk61** [datacarpentry/shell-genomics#136]
The shell-genomics lesson could benefit from an explanation of what FASTQ format is, perhaps starting in the "Working with Files and Directories" episode where students start looking inside the FASTQ files. I see that this is the first topic in the wrangling-genomics lesson, but students will have questions much earlier than this. It would also be more meaningful to them to understand what they are manipulating in these episodes, so they can better understand the why of what they are doing. Furthermore, in the "Redirection" episode it states "We discussed in a previous lesson that the identifier line immediately precedes the nucleotide sequence for each read in a FASTQ file," but this did not happen in a previous lesson, which will lead to further confusion.

**Comment by aschuerch** [comment]
I fully agree. This would mean we would have to shift "Details on the FASTQ format" from [Assessing Read Quality](http://www.datacarpentry.org/wrangling-genomics/00-quality-control/) to shell-genomics, and I would suggest, right after the introduction of `head` in the [working with files and directories episode](http://www.datacarpentry.org/shell-genomics/03-working-with-files/). Can some of you weigh in on this @fpsom @lexnederbragt @crazyhottommy @jrherr @ErinBecker @swang8 @smcclatchy @gedankenstuecke ?

**Comment by gedankenstuecke** [comment]
I agree, this would make a lot more sense! 👍

**Comment by fpsom** [comment]
@aschuerch That is actually a good point, thanks @jrkirk61! However I'm a bit unclear so as to where the _"Details on the FASTQ format"_ should be moved; if it's the first section of the episode on ["Working with files and directories"](http://www.datacarpentry.org/shell-genomics/03-working-with-files/) it seems a bit abrupt. Maybe also add a short intro to the ... intro, by stating (for example) that _"FASTQ files are usually received from the sequencing facility and contain the data necessary for further analysis"_?

**Comment by jrkirk61** [comment]
@fpsom No problem! A natural spot seemed to be right at the beginning of the "[Working with files and directories](http://www.datacarpentry.org/shell-genomics/03-working-with-files/)" episode after the "Our data set: FASTQ files" header. However, I would agree that adding a short intro would help make a more natural transition into the topic. Another possibility would be to introduce it even sooner in the "Genomics Organization" lesson, episode "[Planning for NGS Projects](http://www.datacarpentry.org/organization-genomics/02-project-planning/)", in the "Retrieving samples from the facility" section.

**Comment by crazyhottommy** [comment]
yes, I agree it is always helpful to know what kind of data we are working on before any analysis.
@jrkirk61 's idea could be right. A small introduction of the data sets can be helpful in the very beginning.

**Comment by gentlenikki** [comment]
I agree that a short intro into the FASTQ format would be useful at the beginning of the ["Working with files and directories"](http://www.datacarpentry.org/shell-genomics/03-working-with-files/) episode. It would also really help to provide context for the "grep -B1 -A2" example in the ["Redirection"](http://www.datacarpentry.org/shell-genomics/04-redirection/) episode.

**Comment by ErinBecker** [comment]
Looks like there is widespread agreement on moving this section. Could one of the Maintainers please put in a PR? @gedankenstuecke @aschuerch @swang8 @smcclatchy

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/164

**Comment by ErinBecker** [comment]
Thanks @aschuerch! It looks like this didn't automatically close when you merged your PR (https://github.com/datacarpentry/shell-genomics/pull/164), so I'm closing now.
