### ISSUE TITLE
Episode 03: `echo` explanation

### ISSUE THREAD

**Issue by bebatut** [datacarpentry/shell-genomics#143]
Hi,

In the episode 03, the `echo` command is used:

![screen shot 2018-05-18 at 17 35 34](https://user-images.githubusercontent.com/1842467/40243987-f45c4068-5ac1-11e8-9fc7-161c6767a776.png)

But I feel it is not really fitting there, specially because it is not really explained and the output there is the same as the `ls *.fastq`. So I am not sure if it could not be really confusing for learners. What do you think?

Bérénice

**Comment by gedankenstuecke** [comment]
That's a good point. Having a more general introduction/description could be good, and if it's only `echo 'If you enter *.fastq it will match the following'` or similar?

**Comment by ajank** [comment]
Hi Bérénice and Bastian,

I would propose that the learners see the difference between `echo` and `ls` by comparing the outputs of `echo *.missing` and `ls *.missing` (where `*.missing` does not exist). For this purpose, I suggest to move the introduction of `echo` to this exercise.

Alek

**Comment by ErinBecker** [comment]
Closing this issue as it is addressed in #172. Thanks @bebatut, @gedankenstuecke and @ajank!
