### ISSUE TITLE
New Potential Challenge Question

### ISSUE THREAD

**Issue by brittneykeel** [datacarpentry/shell-genomics#147]
This comment is being submitted as a contribution to this lesson as part of instructor training. As an additional challenge to check the understanding of the 'ls -F' command, one might have a directory, call it say 'practice' that contains three items: a directory called test1, a file called test2, and a directory called test3. The students can then be asked to determine which of the contents are directories and which are files.

**Comment by aschuerch** [comment]
Thank you for your suggestion for a challenge @brittneykeel ! Could you indicate the place where this would need to be included in the lesson?

**Comment by brittneykeel** [comment]
This challenge could be placed right after the discussion of the ls -F command.

**Comment by aschuerch** [comment]
In the current lesson, there is already a different challenge shortly after this which might be enough. I am closing this issue.
