### ISSUE TITLE
Issue with grep exercise solution in episode 04, "Redirection"

### ISSUE THREAD

**Issue by mkweskin** [datacarpentry/shell-genomics#150]
I don't think the solution to the exercise `How many reads in the SRR098026.fastq file contain at least two regions of 5 unknown nucleotides in a row, separated by any number of known nucleotides?` is right.

The provided solution, `grep "NNNNN*NNNNN"` will also match two group of Ns separated by more Ns for example, `CNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN`

When we taught this, some experienced users came up with regex that does the intended match, such as: `grep "NNNNN[ACGT]\+NNNNN"` It doesn't seem like introducing regex is the best way to go, so I'm not sure about how the exercise or solution can be modified.

**Comment by swang8** [comment]
@mkweskin Agree, regex is complicated for shell beginners. Maybe we can modify the question to  `How many reads in the SRR098026.fastq file contain at least two regions of 5 unknown nucleotides in a row, separated by any number of known**/unknown** nucleotides?`

**Comment by mkweskin** [comment]
I'm leaning towards suggesting dropping the exercise and the preceding paragraph. It's the only place that wildcards are shown in a grep string. Wildcards in grep operate differently than bash globbing and I can't think of an easy way to avoid discussing regular expressions or another way to do the exercise without them.

My understanding of grep regex is that the `*` in `grep "NNNNN*NNNNN"` means 0 or more `N`s (the charcter preceding the `*`). For example, the sequence `ANNNNNNNNAAAAAAAAAAANNNNNNNNNAAAAAA` from `SRR098026.fastq` matches `grep "NNNNN*NNNNN"` on the second set of nine `N`s: `NNNNNNNNN`, it's a coincidence that it also matches the intended solution.

For example, this series of 9 `N`s matches:
`$ echo NNNNNNNNN | grep "NNNNN*NNNNN"`
`NNNNNNNNN`

but this does not match:
`$ echo NNNNNANNNNN | grep "NNNNN*NNNNN"`
` `

**Comment by swang8** [comment]
That's right. Need to add a dot `.` to make it work.
`$ echo NNNNNANNNNN | grep "NNNNN.*NNNNN"`

I will wait to see if others have to say about removing or keeping this.

**Comment by aschuerch** [comment]
It's a problematic exercise. I second the suggestion of dropping it, given that there is more than enough material in the lesson. Could we have another opinion on it before deciding to drop it @smcclatchy @gedankenstuecke @fmichonneau ?

**Comment by fmichonneau** [comment]
I agree this does seem pretty advanced. If there is already too much in the lesson, then I don't see a problem with dropping the exercise. You may want to make sure that the skills practiced by doing this exercise are covered somewhere else though, and that it doesn't create a long section of teaching without a break to leave learner a chance to apply the skills learned.

**Comment by taylorreiter** [comment]
+1 dropping this exercise! It gave us a lot of trouble in our lesson today.

**Comment by shannonekj** [comment]
The fix would be **grep NNNNN[ACGT]*NNNNN** which would introduce more than the learners have been exposed to thus far. +1 for dropping as well.

**Comment by bredelings** [comment]
+1 for dropping.

**Comment by ErinBecker** [comment]
Thanks @aschuerch. It looks like this didn't close when you merged your PR back in September, so I'm merging now.
