### ISSUE TITLE
change redirect file from .txt to .fa in redirection lesson

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/shell-genomics#154]
In Episode 4: Redirection, bad reads are redirected to `bad_reads.txt`:
```
grep -B1 -A2 NNNNNNNNNN SRR098026.fastq > bad_reads.txt
```
 However it contains full fastq information and so is a fastq file. I propose redirecting to `bad_reads.fastq` instead.

**Comment by raynamharris** [comment]
I agree this would be very useful. It would re-emphasize that this syntax captures all four lines that make a .fastq file a .fastq file. For grep without the -B1 and -A2 files, the bad_reads.txt naming would make sense.

**Comment by aschuerch** [comment]
Thank you @taylorreiter and @raynamharris for raising this issue. I see your point and I agree that it would be clearer if the file would be called `.fastq'.
The problem with this is that we will run into troubles with the wildcards later down the lesson (See the 'File extensions and File extensions - part 2 callouts in the Redirection episode). If we avoid .txt here we will need a step to remove all these training files or another way to exclude them. If you are planning to prepare a pull request on this, please carefully go through the rest of the lesson to see how this would influence the narrative and if this would interfere with the script etc also in the [wrangling-genomics lesson](datacarpentry/wrangling-genomics).

**Comment by taylorreiter** [comment]
Thank you @aschuerch! We will think through this a bit more over the next few days, as well as how it fits into other notes we made about the lessons during our recent workshop, and proceed carefully with changes to make sure the lesson maintains a continuous narrative!

**Comment by ErinBecker** [comment]
Thanks for the discussion team! This appears to have been incorporated in the callout box "File extensions - part 2" in [episode 4](https://datacarpentry.org/shell-genomics/04-redirection/) so I'm closing this issue. Please re-open if I'm reading this incorrectly and it hasn't been resolved.
