### ISSUE TITLE
Solution `grep NNNNN*NNNNN` is incorrect

### ISSUE THREAD

**Issue by bredelings** [datacarpentry/shell-genomics#160]
In episode 04-redirection, one of the solutions says that, to find 5 N's, followed by anything, followed by 5Ns, you can type `grep NNNNN*NNNNN filename`.

This is not right, as you can see by running `grep NNNNN*NNNNN filename --color=auto`.

Grep takes regular expressions, so "*" does not mean "anything".  It means "repeat the previous character 0 to infinity times".  Thus, the grep command above matches only Ns.  This seems to be a mistake based on assuming that `*` matches anything in grep, since it matches anything when expanding filenames in the shell.  In fact the pattern above matches 9 or more Ns in a row.

The correct command would be `grep NNNNN.*NNNNN ...`.  Note the dot (`.`) in from of the `*`.  However, I don't think users have learned regular expressions at this point in the course.

**Comment by bredelings** [comment]
Perhaps `grep NNNNN[ATGC]+NNNNN` would fit the question better.

**Comment by swang8** [comment]
Thanks, @bredelings. 
Since regex has not been covered in the class yet, many instructors favored removing this exercise. What do you think? See the discussion here: https://github.com/datacarpentry/shell-genomics/issues/150

**Comment by bredelings** [comment]
Closed as dup of #150 .
