### ISSUE TITLE
Episode 05: Is it necessary to pit "geeks" and "non-geeks" against each other?

### ISSUE THREAD

**Issue by diyadas** [datacarpentry/shell-genomics#161]
Hi, I was reviewing the material in preparation for a workshop @cypranowska and I are teaching next week, and I saw this picture in the material:
![image](https://user-images.githubusercontent.com/7118569/43659339-9349c1ca-9710-11e8-955f-e737cb48636b.png)

I appreciate that the material is trying to explain the benefits of automation. However, I find this particular image alienating and counter to my goals as an instructor in creating a welcoming environment for all. Not everyone identifies as a "geek" (or wants to), and this is vaguely insulting to "non-geeks," which this image seems to imply is anyone who doesn't already write scripts.

I'd propose that instead of:

>Scripts let you save commands to run them and also lets you put multiple commands together. In the plot below, this is where you win, because you are automating your work.
>![image](https://user-images.githubusercontent.com/7118569/43659339-9349c1ca-9710-11e8-955f-e737cb48636b.png)

This is rewritten to state:
>Scripts let you save commands to run them and also let you put multiple commands together. Though writing scripts may require an additional time investment initially, this can save you time as you run them repeatedly. Scripts can also address the challenge of reproducibility: if you need to repeat an analysis, you retain a record of your command history within the script.

I'm happy to issue a PR / accept additional edits to my text - I'm aware that my revised phrasing could also use improvement.

**Comment by swang8** [comment]
@diyadas Thank you very much. I think what you said makes sense. You are very much welcome to issue a PR.
