### ISSUE TITLE
memory allocation error caused by hyphens in file name when using Git Bash to connect to AMI

### ISSUE THREAD

**Issue by diyadas** [datacarpentry/shell-genomics#162]
We had a learner using Git Bash to connect to the AMI to follow along in Episode 5. 

For some reason, `nano bad-reads-script.sh` triggers some memory allocation errors. As does vi. As does restarting Git Bash and trying with another AMI. 

We had a helper who guessed it was the sudden appearance of hyphens at this point. Trying with underscores instead of hyphens worked. 

I'm not sure what exactly caused the issue but if this is something facing many Git Bash/Windows users, it may be a small enough thing to use underscores instead of hyphens at this point.

**Comment by aschuerch** [comment]
Thank you for reporting!

**Comment by JasonJWilliamsNY** [comment]
Arizona BugBBQ - Technology/data maintainers should address these issues. In this case - we only support Putty for windows users.
