### ISSUE TITLE
Episoide 03: more on the command ls

### ISSUE THREAD

**Issue by destadey** [datacarpentry/shell-genomics#167]
In the "Examining the contents of other directories"  section, we can add a statement about the option "-lh"  as one of the important options frequently used in genomics to get the information about the contents of a working directory with the file size in human readable format.
as an example  we can use the same  directory "ls -lh dc_sample _data" and display the output.

**Comment by aschuerch** [comment]
Thank you for the suggestion!

**Comment by ErinBecker** [comment]
Arizona Bug BBQ - Thank you @destadey for this suggestion. Since there is already an exercise for exploring `ls` and reading the man page, we are closing this issue as it adds additional content to an already overloaded lesson.
