### ISSUE TITLE
Link to stylesheet for reference page broken

### ISSUE THREAD

**Issue by mdehollander** [datacarpentry/shell-genomics#169]
Suggested a fix with a PR: https://github.com/datacarpentry/shell-genomics/pull/168, but other lessons use a different approach.

**Comment by ErinBecker** [comment]
The reference page is rendering properly for me now. Can anyone confirm if this is still an issue on some systems?

![Screen Shot 2019-03-18 at 4 13 08 PM](https://user-images.githubusercontent.com/19176319/54569616-c9bd6500-4998-11e9-9d75-889937a8b94e.png)

**Comment by mdehollander** [comment]
I can also confirm it renders ok now, but I don't see when and how this has been fixed however.

**Comment by ErinBecker** [comment]
It's broken again for me: 

![Screen Shot 2019-04-10 at 12 02 18 PM](https://user-images.githubusercontent.com/19176319/55906200-8c5b8a00-5b88-11e9-9f10-6e2b8457ad2c.png)

@fmichonneau has been talking about converting all of the Genomics lessons to use remote themes. @fmichonneau would this fix these recurring styling issues or does that need to be a different solution?

**Comment by fmichonneau** [comment]
it seems to be working (on the online version). Is it broken locally for you?

Yes, using remote themes would make this kind of issues much less likely.

**Comment by aschuerch** [comment]
The stylesheet in Setup is also broken for me https://datacarpentry.org/shell-genomics/setup.html, see also issue #185
