### ISSUE TITLE
Episode 3: LS/Echo/Wildcard

### ISSUE THREAD

**Issue by BobLiterman** [datacarpentry/shell-genomics#170]
Hello! 

In Episode 3 (Working with Files and Directories), the lesson begins with the wildcard. It has learners ls, ls *.fastq, and then also echo *.fastq. 

It strikes me that the output from all  of these commands is identical (ls = ls *.fastq = echo *.fastq) which may undermine the intent of the lesson. 

When I taught this during my checkout, I created a new file (test.txt) on the fly with touch, to show that I could 'ignore' that file with wildcards. It really made the results clearer I think. 

Perhaps rather than an empty file, the learners could take a minute to add some metadata to a text file that corresponds to the reads their using? Just something that's not a FASTQ in the directory so ls  != ls *.fastq. 

Thanks!

**Comment by aschuerch** [comment]
Thank you for this suggestion @BobLiterman, and have a look at pull request #172 which addresses ls/echo. Does this solve the issue?

**Comment by BobLiterman** [comment]
Oh that looks great! My issue can be closed.

Best,
Bob
