### ISSUE TITLE
Episode 3: Root versus Home

### ISSUE THREAD

**Issue by BobLiterman** [datacarpentry/shell-genomics#171]
Hello again! 

In Episode 3,  there is an aside about the distinction between home and root that doesn't come up again in the lesson is quite a stark detour relative to the other things being taught. Perhaps this could be moved back  to Episode 2 where learners are learning about navigating around?

Thanks!
Bob

**Comment by ErinBecker** [comment]
Arizona Bug BBQ - Thanks @BobLiterman - our group thinks that this callout could fit in either place, but also notes that call outs are optional and can be introduced by Instructors as needed. If you feel strongly about this change, a PR would be great.

**Comment by akshayparopkari** [comment]
This issue is brought up again for discussion in #269
