### ISSUE TITLE
Repeated sentence in Writing Scripts episode

### ISSUE THREAD

**Issue by hughcross** [datacarpentry/shell-genomics#173]
In the Writing Scripts episode, this sentence is repeated twice:  

> Scripts let you save commands to run them and also lets you put multiple commands together.

This appears in the description paragraph after the heading **Writing Scripts**, which is the second section of this episode.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/187
