### ISSUE TITLE
suggestion to remove section from Redirection episode

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/shell-genomics#177]
I'm suggesting to remove "File manipulation and more practice with pipes" from the Redirection episode. With the Wrangling Genomics Integration in #175, we have added for loops to the redirection lesson. The impetus of this was to reduce cognitive burden in the Wrangling Genomics episodes by introducing all base bash commands in Shell Genomics that are used by Wrangling Genomics. However, this increases the lessons size substantially. 

Therefore, I propose we remove "File manipulation and more practice with pipes" from Redirection. This section primarily covers `cut` and `sort`. These two commands are not used in the Wrangling Genomics lesson. I think they are useful commands, but add unnecessary material for the workflow. Alternatively, they could be moved to an optional shell lesson in case this workshop is taught over a longer period of time (i.e. > 2 days).

Thoughts?

**Comment by taylorreiter** [comment]
Note there is an exercise in the next lesson, Writing scripts and working with data, that uses cut. If we choose to remove this section, that exercise would also need to be removed or changed.

**Comment by aschuerch** [comment]
I clearly see the need to diminish the lesson material and it makes sense to cut down on 'cut' and 'sort' even though they are certainly useful. Also, moving them to an optional shell lesson makes sense.

**Comment by ErinBecker** [comment]
Thank you for the suggestion @taylorreiter. It sounds like there is maintainer support for this change, so I'll mark it as help-wanted for the next release.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/187
