### ISSUE TITLE
build out introduction to basename more in 04 Redirection

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/shell-genomics#179]
The end of 04 Redirection introduces `basename`, but it's the first time the learners are seeing it and it's inside of a `for` loop...that's a lot of cognitive overload! At our recent workshop 2019-02-04-boston, I broke it out like this first:

## Using Basename in for loops
Basename is a function in UNIX that is helpful for removing a uniform part of a name from a list of files. In this case, we will use basename to remove the *.fastq from the files that we’ve been working with. 

```
$ basename SRR097977.fastq .fastq
```

We see that this returns just the SRR accession, and no longer has the .fastq file extension on it.

```
SRR097977
```

If we try the same thing but use `.fasta` as the file extension instead, nothing happens. This is because basename only works when it exactly matches a string in the file.

```
$ basename SRR097977.fastq .fasta
```
```
SRR097977.fastq
```

Basename is really powerful when used in a for loop. It allows to access just the file prefix, which you can use to name things. Let's try this.

Inside our for loop, we create a new name variable. We call the basename function inside the parenthesis, then give our variable name from the for loop, in this case `${filename}`, and finally state that `.fastq` should be removed from the file name. It’s important to note that we’re not changing the actual files, we’re creating a new variable called name. The line > echo $name will print to the terminal the variable name each time the for loop runs. Because we are iterating over two files, we expect to see two lines of output.

```
$ for filename in *.fastq
> do
> name=$(basename ${filename} .fastq)
> echo ${name}
> done
```

Exercise:
Print the file prefix of all of the `.txt` files in our current directory.
Solution:
```
$ for filename in *.txt
> do
> name=$(basename ${filename} .txt)
> echo ${name}
> done
```

One way this is really useful is to move files. Let's rename all of our .txt files using `mv` so that they have the years on them, which will document when we created them. 

```
$ for filename in *.txt
> do
> name=$(basename ${filename} .txt)
> mv ${filename}  ${name}_2019.txt
> done
```

Exercise
Remove `_2019` from all of the `.txt` files. 
Solution
```
$ for filename in *_2019.txt
> do
> name=$(basename ${filename} *_2019.txt)
> mv ${filename}  ${name}.txt
> done
```

**Comment by aschuerch** [comment]
Thank you @taylorreiter , I agree that it is too much cognitive overload as it is now. I like how you broke it out. Can you put in a pull request?

**Comment by taylorreiter** [comment]
I can!

**Comment by ErinBecker** [comment]
Thanks @taylorreiter for the PR. I'm going to close this issue as it looks like it has been addressed.
