### ISSUE TITLE
Link to Setup page in Schedule

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#185]
It now directs to a stylesheet-less page with a redirection to the general setup page. Should ideally directly link to https://datacarpentry.org/genomics-workshop/setup.html

**Comment by aschuerch** [comment]
This relates to #169

**Comment by ErinBecker** [comment]
Thanks for this @aschuerch. It would be great to have all of the individual setup pages from the Genomics lessons go directly to https://datacarpentry.org/genomics-workshop/setup.html through a redirect. @fmichonneau, could you show me how to do this for one of the pages and I'll take care of the rest?

**Comment by aschuerch** [comment]
Closed with #217
