### ISSUE TITLE
Menu in 'Transferring Data Between your Local Machine and the Cloud' not working

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/shell-genomics#186]
In 05-writing-scripts. The choice menu for "AWS_Windows" and "AWS_Unix" seems to not do something at all (tested in Firefox). I suspect it is a missing javascript paragraph as seen in https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/02-logging-onto-cloud.md

**Comment by ErinBecker** [comment]
Closed with #215

**Comment by ErinBecker** [comment]
Actually, it looks like this didn't quite work. I'm re-opening the issue and making a note to myself to look into this tomorrow.

**Comment by ErinBecker** [comment]
I haven't been able to figure out how to get this to work so am thinking of putting the two different options in "solutions" boxes like are used on the [setup page](https://datacarpentry.org/genomics-workshop/setup.html). I'll put in a PR with this option today.

**Comment by ErinBecker** [comment]
Ok, so upon closer inspection, the reason this isn't working is because there isn't any content in the Unix section, so when the toggle is switched over to Unix, the display doesn't change. I think @ACharbonneau had mentioned populating this content at one point, but I may be misremembering.

**Comment by ACharbonneau** [comment]
That's weird, I did fix it. Maybe that bit got lost in the PRs? Let me see if I can re-fix it
