### ISSUE TITLE
Site links on 'lessons' page point into github repo

### ISSUE THREAD

**Issue by ctb** [datacarpentry/shell-genomics#19]
Hi, it is confusing to me that on

http://www.datacarpentry.org/lessons/#genomics-workshop

the "Introduction to the command line - site" link points to https://github.com/datacarpentry/shell-genomics/tree/gh-pages/lessons, rather than to a rendered page. Is this intentional?

If not, I can try to find the source to that lessons page and fix it there; just let me know where the correct URL is (or I can try to find that, too ;)

**Comment by tracykteal** [comment]
It should point to the rendered pages. Thanks for pointing that out. It's been updated.
