### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/shell-genomics#198]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by aschuerch** [comment]
- Instructor notes box can be checked if  #199 is fixed 
- Links box can be checked if #199 is fixed

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by ErinBecker** [comment]
I've confirmed that the call out boxes (exercises, discussions, tips, etc) render correctly and have checked off this item.

**Comment by ErinBecker** [comment]
Cleaned up file structure (removed unused figures and pdfs) in https://github.com/datacarpentry/shell-genomics/pull/235. @fmichonneau - could you please take a look and merge before doing the release on this lesson (if one of the Maintainers doesn't get to it first?)

**Comment by ErinBecker** [comment]
Checked off the first three items based on all code working smoothly in UA workshop. After #235 is merged, I think this lesson is ready for release.

**Comment by ErinBecker** [comment]
With the merging of #235, this checklist is now complete and lesson is ready for publication!

**Comment by ErinBecker** [comment]
Awesome work @datacarpentry/shell-genomics-maintainers  and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3260560
