### ISSUE TITLE
shell-genomics/01-introduction: pwd tab completion output

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/shell-genomics#203]
The output for the `pwd` command will look different on the docker image or if someone is trying it on a different system. Comment that the output will vary (not a big deal) and is dependent on your system.

**Comment by samnooij** [comment]
Good point! I just opened a pull request based on the different output I got on the Amazon Cloud instance that I was testing for a workshop. It sounds like a sensible solution to add a comment like that, instead of changing to whatever you may see on your (test) machine.

**Comment by aschuerch** [comment]
Closed with pull request #263
