### ISSUE TITLE
shell-genomics/04-redirection: braces aren't explained in for loop variable

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/shell-genomics#206]
The $ and > symbols are explained when introducing for loops but braces {} around variable is not explained

**Comment by aschuerch** [comment]
Dear Jason, thank you for reporting. A pull request would be highly appreciated.

**Comment by ErinBecker** [comment]
@ryneches - wanna take a stab at this? 😄

**Comment by ryneches** [comment]
Does this help?

**Comment by ryneches** [comment]
Well, @aschuerch approved my PR, so I guess let's close the bug?
