### ISSUE TITLE
Local Rendering/Theme

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/shell-genomics#216]
I was updating some code for this repo in https://github.com/datacarpentry/shell-genomics/pull/201 and https://github.com/datacarpentry/shell-genomics/pull/215 and I could *only* get the page I was working on to render locally to test the selection code by physically copying the entire page into my local cloud-genomics repo and rendering that. This shell-genomics repo just would not render no matter what I did. 

The initial problem was that this repos `_config.yaml` file has a theme line (which none of the rest of the Genomics lessons seem to be using), but does not have a `Gemfile` in the repo, and so local renders can't find the theme. 

I added a `Gemfile` with the text:
```
source 'https://rubygems.org'
gem "github-pages", group: :jekyll_plugins
```
to my local shell-genomics repo, which got it past that error, but then I got a new Jekyll error that I couldn't resolve. Here's the error I'm getting:
```
Amandas-MacBook-Pro-2:shell-genomics amanda$ make serve
jekyll serve
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/amanda/.gem/ruby/2.3.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
	from /Users/amanda/.gem/ruby/2.3.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
	from /Users/amanda/.gem/ruby/2.3.0/bin/jekyll:22:in `load'
	from /Users/amanda/.gem/ruby/2.3.0/bin/jekyll:22:in `<main>'
```

I'm not familiar enough with Jekyll to suggest any fixes, but I don't think it's a problem with my install because I can render cloud-genomics just fine.

**Comment by aschuerch** [comment]
thank you @ACharbonneau for reporting.

**Comment by aschuerch** [comment]
I will close this because #217 , please feel free to re-open if the issue remains
