### ISSUE TITLE
Cognitive load towards end of lesson

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/shell-genomics#219]
I just finished teaching this lesson and, overall, I think it went pretty well and the material is very good. The only concern that I had was the introduction of loops, scripts, and variables in quite quick succession towards the end. I found it very difficult to manage the cognitive load in this section and I think I a few learners got lost at this stage.

Is there a way that we can avoid introducing all of these (quite challenging) concepts one after the other like this? Could some of these concepts be introduced instead in the data wrangling lesson? Or would you prefer not to introduce any new shell concepts in that lesson?

Given that the Shell lesson needs to be covered entirely before Data Wrangling, I worry that there is very little time remaining for the latter if so much is spent explaining loops, `${variable_substitution}`, etc in the former.

**Comment by aschuerch** [comment]
Thank you Toby, I am glad that teaching the lesson went well. I think your concern about the end of the lesson is in line with #206 and #207

**Comment by tobyhodges** [comment]
Hi Anita, yes you're probably right. I'm sorry that I didn't read through those discussions already. I'll close this now, then. If necessary, I can contribute further to ongoing discussions on those linked issues.
