### ISSUE TITLE
`bad_reads.txt` is not divisible by 4

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/shell-genomics#224]
`bad_reads.txt` is not divisible by 4. It seems to be inserting `--` lines between reads which aren't consecutive for some reason.

We still aren't sure why it does that.

**Comment by fmichonneau** [comment]
it's a feature of the -A and -B flags.

This SO question has some ways around this: https://stackoverflow.com/questions/2168065/how-do-i-get-rid-of-line-separator-when-using-grep-with-context-lines

**Comment by aschuerch** [comment]
fixed with #258
