### ISSUE TITLE
Introduce -v flag of grep

### ISSUE THREAD

**Issue by esebesty** [datacarpentry/shell-genomics#227]
There is an [open issue](https://github.com/datacarpentry/wrangling-genomics/issues/147) in the wrangling-genomics repo about the `-v` flag for grep. `grep -v` is used during an exercise, but the `-v` flag is not introduced before.

I guess it would be good to add an example/exercise on it here, in the shell-genomics lesson. I would be happy to deal with this as my instructor checkout issue.

**Comment by aschuerch** [comment]
Hi @esebesty, thank you for the offer. I would suggest we wait for the discussion #230. Maybe you can weigh in?

**Comment by aschuerch** [comment]
now introduced with #258
