### ISSUE TITLE
broken link in slides.md

### ISSUE THREAD

**Issue by ytakemon** [datacarpentry/shell-genomics#23]
Noticed a broken link to nano1.png and nano2.png under the "Writing files" section of slides.md

**Comment by smcclatchy** [comment]
The link to the image appears to be fixed, however, the link to the Software Carpentry shell tutorial is broken beneath Where can I learn more about the shell?
http://www.datacarpentry.org/shell-genomics/05-writing-scripts/

**Comment by aschuerch** [comment]
I changed the broken link to https://swcarpentry.github.io/shell-novice/reference
