### ISSUE TITLE
pscp download command needs clarification

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/shell-genomics#237]
When uploading files using pscp, the command:
C:\User\your-pc-username\Downloads> pscp.exe local_file.txt dcuser@ip.address:/home/dcuser/

does not seem to work. Using AWS, the working command is C:\User\your-pc-username\Downloads> pscp.exe local_file.txt dcuser@ec2-54-88-126-85.compute-1.amazonaws.com:/home/dcuser/

Someone more familiar with pscp than me should weigh in on this, but it looks like using "@ip.address" is not right and @ec2-XXX-XXX-XXX-XXX should be used.

**Comment by aschuerch** [comment]
There is an ongoing pull request #228 , maybe @ErinBecker could you have a look?

**Comment by ErinBecker** [comment]
Sorry for the slow response on this @hoytpr. I'll go ahead and make this change now. Also pinging @ACharbonneau in case this affects the cloud lesson.

**Comment by hoytpr** [comment]
This looks good @ErinBecker and thanks for your attention to this issue. @aschuerch it should be your call now to merge/close. Thanks!

**Comment by aschuerch** [comment]
Thank you @hoytpr and @ErinBecker!
