### ISSUE TITLE
03-working-with-files and less searching

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/shell-genomics#238]
The lesson says:  “less searches from the current location and works its way forward. “ 
(rhetorical) Then how do we know which TTTTT is the first instance? We use `g`, however when using `g` on a fastq file it is hard to know you are at the beginning of the file unless you scroll up a couple lines. Add "Scroll up a couple lines on your terminal to verify you are at the beginning of the file". Alternatively, when using the `head` command immediately afterwards mention how it confirms `g` sent you to the top of the file.

**Comment by aschuerch** [comment]
Thanks. I would prefer the first suggestion ("scroll up a couple of lines...") to practice navigating with less

**Comment by akshayparopkari** [comment]
Fixed in #275
