### ISSUE TITLE
Word change in 03-working-with-files copy vs backup

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/shell-genomics#239]
In the exercise: "Create a copy of each of your FASTQ files"
Should be "Create a backup of each of your FASTQ files" 

or if you want it to be easier:
"Create a backup of each of your FASTQ files using `cp`"

**Comment by aschuerch** [comment]
Hi @hoytpr , I agree with your suggested wording (I like the second suggestion). Would you be willing to put in a pull request?

**Comment by hoytpr** [comment]
Sure. Take a few minutes.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/243
