### ISSUE TITLE
Adding an instruction during `rm` 

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/shell-genomics#240]
During the lesson on `rm`, the lessons says:
"If you enter n (for no), the file will not be deleted. If you enter y, you will delete the file. This gives us an extra measure of security, as there is one more step between us and deleting our data files."

A statement saying "You should enter `n` for now." should be inserted so that the following `rm -r backup` will work as expected.

**Comment by aschuerch** [comment]
Thanks for raising this issue. This will indeed make the flow of the lesson less ambiguous.
