### ISSUE TITLE
04-redirection grep exercise solution: expand if kept

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/shell-genomics#241]
If the grep part of the lesson is kept, the exercise searching for GNATNACCACTTCC and AAGTT has solutions that show the commands to use, but not the outputs. The outputs would help the learner know they are still on track.

**Comment by aschuerch** [comment]
Thank you for raising this. A pull request would be welcome!

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/243
