### ISSUE TITLE
05-writing-scripts has exercise with no solution

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/shell-genomics#242]
In the lesson about creating a script `bad-reads-script.sh` the exercise says:
"We want the script to tell us when it’s done."
There is no solution (output) for the learners that includes the "Script finished!".

**Comment by aschuerch** [comment]
It would indeed be good to add the solution to the exercise

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/243
