### ISSUE TITLE
Adding a Unix cheat sheet for students

### ISSUE THREAD

**Issue by taylorpaisie** [datacarpentry/shell-genomics#244]
Adding a link to a Unix cheat sheet would be a useful for students to refer to during the workshop.  Here is a link for a Unix cheat sheet:  https://files.fosswire.com/2007/08/fwunixref.pdf

**Comment by aschuerch** [comment]
Thanks @taylorpaisie, I think this would make a fine addition to https://datacarpentry.org/shell-genomics/reference.html, under the heading external reference

**Comment by akshayparopkari** [comment]
fixed in #279
