### ISSUE TITLE
Adding a few links to resources - background knowledge

### ISSUE THREAD

**Issue by mstagliamonte** [datacarpentry/shell-genomics#247]
Hi,

After helping to teach this workshop, I realized several students needed some background on how Illumina sequencing works in order to better comprehend the workflow. I would suggest to add a few links for the students to look up in their own time:

**Brief overview on paired-end technology:**
https://www.youtube.com/watch?v=womKfikWlxM
https://www.illumina.com/science/technology/next-generation-sequencing/plan-experiments/paired-end-vs-single-read.html

**Illumina quality phred scores:**
https://en.wikipedia.org/wiki/Phred_quality_score
https://en.wikipedia.org/wiki/FASTQ_format

**Samtools flagstat quick de-code:**
https://broadinstitute.github.io/picard/explain-flags.html

Hope it helps.

Best,
Max

**Comment by aschuerch** [comment]
Thank you Max!
