### ISSUE TITLE
MacOS will now default to ssh

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#251]
FYI

> It has been announces that the next MacOS will have Zsh as the [default shell](https://support.apple.com/en-us/HT208050) this lesson assume that by default the shell on macos is bash. 

Please read the discussion here: https://github.com/swcarpentry/shell-novice/issues/978#issuecomment-510772067

I don't think this will impact this lesson, because everything is run through AWS. However, we should update the setup instructions for learners working through these lessons locally or who are using a different remote/cloud service. There are [install instructions for zsh here](https://sourabhbajaj.com/mac-setup/iTerm/zsh.html).

**Comment by akshayparopkari** [comment]
Thanks for bringing this up, @ErinBecker.  

Here are a couple of thoughts -
* I haven't come across any issues when I attempted working through this lesson on MacOS Catalina using `zsh` shell.

* For self-learners using local machines, MacOS users can switch between `bash` and `zsh` shells -
```sh
# Switch to bash shell by running -
bash

# Run through the lesson contents
# episode 1
# episode 2
# episode 3
# episode 4
# episode 5
# episode 6

# Exit out of bash shell, back to zsh shell by running -
exit
```

I don't believe `bash` --> `zsh` switch require any changes in the lesson content. Are you suggesting that the setup include a pointer similar to the second bullet point above?

**Comment by akshayparopkari** [comment]
I am closing this issue without a PR. There isn't an obvious direct change addressing this issue. Please feel free to reopen to suggest lesson improvements 🙂
