### ISSUE TITLE
lesson contribution - submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#256]
As part of the checkout process I had a good thought about how to contribute and improve one of the current lessons. To be honest I think they are all pretty amazing already, well thought of, clear structured and accessible even for someone with little background and limited data wrangling and command line skills.

One thing I noticed which might be an improvement, especially for those participants who already have a little bit of experience with the command line and are planning to use it more frequently is to give a few more useful tips and additional information in following episode: 

https://datacarpentry.org/shell-genomics/03-working-with-files/index.html

Under section Command History 
(if you are a bit nerdy {aren't we all here} you could now hit Ctrl+U to open the HTML file in FF or Chrome ;) )

From L436 - 442 it is mentioned that one could repeat a certain command found in the history by using the ! (exclamation mark) followed by the history entry number. Certainly a very useful tip, but what is missing in my opinion is:

A) a very brief statement that this is called a 'HISTORY EXPANSION', so that the trainees know what they need to search for in the bash man pages or what to type into their search engine of choice.

B) 1-2 practical tips they could immediately try for themselves like following: !! re-executes the previous command or !cat (or any !string) executes the most recently executed command that begins with the letters cat and a lot more…

I understand we don't want to go into too much detail at this stage of the lesson, but adding 1-2 lines (maybe as a popup window to avoid breaking the main flow of the lesson) here would be useful background information, especially for genomics work as I can speak from my own experience. (Sidenote: I like the possibility of reusing the last part of the last command with !$ when I do cat path/to/myfiles/file.txt and I want to edit this file I just hit nano !$.)

**Comment by akshayparopkari** [comment]
@ErinBecker, thanks for forwarding the feedback. 

I think the current lesson content conveys information about bash history for most use cases. Also, couple of sections later, the lesson covers `rm`, and users may accidentally run `!!` or `!$` and delete required files. I would rather play it safe to avoid interruptions in instruction flow. Thoughts, @datacarpentry/shell-genomics-maintainers?

**Comment by aschuerch** [comment]
I agree with @akshayparopkari , I also feel safer not pointing this out. We could, however, link explicitly to the gnu html bash manuals (https://www.gnu.org/software/bash/manual/html_node/index.html) in our reference page for further information for the more advanced users. What do you think?

**Comment by akshayparopkari** [comment]
> link explicitly to the gnu html bash manuals

I agree, @aschuerch 👍 ✅ 

It will be beneficial to include Bash manual in the references under _Manuals_. One approach is to add a line - **Check Bash manual (section 9.3) [INSERT LINK] for advanced interactive`history` usage.** - right before the exercise. This will also serve to improve accessibility on _how to find additional help_ for learners. I can initiate a PR with this change.

**Comment by aschuerch** [comment]
That would be great @akshayparopkari !
