### ISSUE TITLE
feedback from University of Chicago - submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#257]
Overall we really enjoyed being able to motivate our learning of the Unix shell commands by using biological data
We heard from a lot of our learners that they greatly enjoyed the ability to learn in a context where they could see themselves building these skills to further their own research in the future
Our primary difficulty was downloading just the shell data and how to do this on the commandline
it is easy to find on figshare, but difficult to download using wget for example
give an exxample of something you could use `wget` or `curl` for in the lesson (learners wanted to learn about this concept)
`sort` and `uniq` are very useful in genomic data analysis and are not adequately covered here
 after learning how to make directories, project structure should be taught (e.g. create `code`, `doc` directories)
This is a question regarding project management that we have consistently gotten over the past 3 years of workshops and this seems like a great place to teach that.

**Comment by aschuerch** [comment]
Thank you Erin for forwarding this feedback. Regarding the raised points:
- downloading the data would part of the setup instructions on the genomics-workshop repo
- sort and uniq are part of the Extras - > File manipulation. Pull request #273 tries to link this material better to the main lesson
- Project management is covered in https://datacarpentry.org/shell-genomics/06-organization/index.html  
I suggest to close this issue with merging of #273

**Comment by aschuerch** [comment]
I will close this issue, feel free to re-open if necessary!
