### ISSUE TITLE
Add note/tip on hot-key for terminal clearing (contribution for instructor training)

### ISSUE THREAD

**Issue by sirselim** [datacarpentry/shell-genomics#265]
Suggested addition to the Shell Genomics introduction (https://datacarpentry.org/shell-genomics/01-introduction/index.html).

The "How to access the shell" section discusses the use of `clear` to clear information from the displayed terminal window. I would like to suggest that it might be nice to have a note or tip underneath that states the the same thing can be achieved with the hot-key combination of `Ctrl+l`. 

I guess there is the argument for not bombarding trainees with extra information, but I'm constantly getting asked if there are hot-key combinations for various commands so I think it doesn't really hurt to include some of the 'main' ones we use. It can be stated that the participants don't have to dwell on it, it's just there for those that are interested and want to use such things.

Thoughts? I'm happy to make a pull request if the suggestion is met with approval.

**Comment by aschuerch** [comment]
Hi @sirselim, I think it is a good idea to add this information! A pull request is appreciated.

**Comment by sirselim** [comment]
Hi @aschuerch, thanks. Pull request made.

**Comment by aschuerch** [comment]
thank you @sirselim !
