### ISSUE TITLE
Lesson contribution- Combining flags for shell commands- Instructor Checkout

### ISSUE THREAD

**Issue by genesome** [datacarpentry/shell-genomics#267]
**Lesson:** Introduction to the Command Line for Genomics
**Episode:** Navigating Files and Directories 
https://datacarpentry.org/shell-genomics/02-the-filesystem/index.html

I am Chandra Sarkar, a PhD candidate at University of Nevada-Reno, would like to submit a suggestion for the lesson which covers flags used with commands in the shell. 
In the lesson, _Introducing the Shell_, learners start using flags with the ```$ ls``` command.
```bash
$ ls -F
```
In the next lesson, we get introduced to ```$ ls -a``` flag. I think at this point, it is very helpful to mention/teach that in most commands these flags can be combined together to obtain the desired results/output. So maybe something like this:
```bash
$ ls -Fa    ###combining flags -F and -a
### or ###
$ ls -la   ###combining flags -l and -a
```
In genomics especially, knowing that flags are combined really useful when running a lot of softwares from command line. Especially frequently used commands for like:
```bash
$ tar -xvzf File2BeExtracted.tar.gz  ###for unzipping tar files
```
Sometimes for novice learners it does not click right away that 4 different flags (x, v, z, and f in this case) are combined together for the command ```tar```. It seems more like a part of the command itself. Hence, I was thinking this additional bit of information might just be advantageous for future.

**Comment by waydeveldman** [comment]
I like this idea, Chandra. This small addition will enable learners to learn something very important while avoiding confusion at the same time.
