### ISSUE TITLE
Explanation needed for use of # in the shell

### ISSUE THREAD

**Issue by iwema** [datacarpentry/shell-genomics#268]
Lesson: Introduction to the Command Line for Genomics
Episode: Redirection
Topic: Writing for loops
https://datacarpentry.org/shell-genomics/04-redirection/index.html

(Submitted for instructor training checkout.)

In 2 Bash examples under the "Writing for loops" section, the # is used for notes.  However, there is no explanation anywhere in the entire lesson about the function of #s.  This is confusing for someone just starting out and could be clarified with a sentence or two.

e.g.
$ foo=abc
$ echo foo is $foo
foo is abc
$ echo foo is $fooEFG             **# doesn't work**
foo is

**Comment by akshayparopkari** [comment]
Hi @iwema, thanks for raising this issue.

[Project Organization](https://datacarpentry.org/shell-genomics/06-organization/index.html) lesson contains one line on `#` utility, after `Navigating in Nano` blockquote-
>`bash` treats the `#` character as a comment character. Any text on a line after a `#` is ignored by bash when evaluating the text as code.

---

One option to improve lesson clarity is moving the above description line after

> ... sometimes called “squiggle braces”).

in [Redirection](https://datacarpentry.org/shell-genomics/04-redirection/index.html).

Thoughts, @datacarpentry/shell-genomics-maintainers?

**Comment by akshayparopkari** [comment]
fixed in #277
