### ISSUE TITLE
Nav Files and Dir: reference to root dir with no prior definition

### ISSUE THREAD

**Issue by AmyStonelake** [datacarpentry/shell-genomics#269]
In section 2, Navigating Files and Directories, following the command:
$ ls ../../
it says "prints the contents of /home, which is one level up from root dir"

At this point in the lesson,  the concept of the root dir has not been introduced, it is not mentioned until 3. Working with Files and Directories, where the definition of home and root states that "root is two levels above our home directory". 

So...it appears that two different explanations of home and root are given in two different lessons. Perhaps the explanations of home and root can be coalesced from two lessons into one with a clear explanation, maybe even a diagram of the file structure.  

<img width="647" alt="Screen Shot 2020-02-28 at 1 18 49 PM" src="https://user-images.githubusercontent.com/41751561/75575125-8931ec80-5a2d-11ea-85ca-e6e90d387838.png">
<img width="437" alt="Screen Shot 2020-02-28 at 1 24 00 PM" src="https://user-images.githubusercontent.com/41751561/75575157-9bac2600-5a2d-11ea-8ac8-2b01823423da.png">

**Comment by akshayparopkari** [comment]
Hi @AmyStonelake, thanks for bringing up this issue.

I agree with your suggestion to improve and consolidate `home` and `root` definitions. In [Navigating Files and Directories](https://datacarpentry.org/shell-genomics/02-the-filesystem/index.html) lesson, `root (/)` and `home (~)` characters are introduced, it makes sense to move `Home vs Root` blockquote into this lesson from [Working with Files and Directories](https://datacarpentry.org/shell-genomics/03-working-with-files/index.html). One place to include it is inside the `Navigational Shortcuts` section of lesson two.

Thoughts @datacarpentry/shell-genomics-maintainers?

**Comment by akshayparopkari** [comment]
Related to #171
