### ISSUE TITLE
Suggestion for Adding `cut` to "Writing Scripts and Working with Data"

### ISSUE THREAD

**Issue by dr-aheydari** [datacarpentry/shell-genomics#272]
Hello,

I think the content and the organization of the lesson is great, but I was wondering if there could be a short section on using `cut` in addition to `grep`. I believe this would further enhance the learning of the data carpentry learners since using `cut` can help with easier manipulation of data that have fields (or columns), which one could expect from many datasets (with standard formats). Adding this section should not make the learning experience much harder, but it would provide another valuable tool to the beginners' repertoire. 

Thank you for considering this suggestion.

**Comment by akshayparopkari** [comment]
Hi @dr-aheydari, thanks for raising this issue.

`grep` is introduced in episode [4. Redirection](https://datacarpentry.org/shell-genomics/04-redirection/index.html). I do agree with you that `cut` is utilized in combination with grep for tabular data (e.g. CSV, TSV, tab, etc.). I think, when teaching this lesson, the instructor may verbally communicate `grep` + `cut` pipe combination as an independent example to highlight the versatility of bash commands.

Thoughts / inputs, @datacarpentry/shell-genomics-maintainers?

**Comment by aschuerch** [comment]
There is a lesson on cut and grep (See https://datacarpentry.org/shell-genomics/Extra_lesson/index.html). This used to be part of the core lessons but was moved to Extras to make some room in the lesson. Does this lesson cover what you suggested?

**Comment by akshayparopkari** [comment]
Thanks @aschuerch 👍

I wasn't aware of the extra lesson on file manipulation. I'm happy to be learning new things about this lesson. Also, I have been wondering about the inclusion of `shell_data/sra_metadata/SraRunTable.txt` was included in the lesson since it isn't referenced in any episodes. I see that it is used in the extra lesson ✅

**Comment by aschuerch** [comment]
@akshayparopkari I think embedding of the extra content could be improved. Have a look at pull request #273 for an extra callout to point instructors and/or self-guided learners to the extra material. I've put the callout where the material used to be.

**Comment by dr-aheydari** [comment]
@aschuerch Thank you very much for pointing me to the "Extra Lesson" section. I understand why it would be hard to include `cut` and `grep` in the lesson and cover all the material. Thank you for your explanation.

**Comment by aschuerch** [comment]
Thanks for the feedback @dr-aheydari, I am closing this issue now.
