### ISSUE TITLE
Typos and additional exercise 

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#28]
I am writing to make contribution to “Genomics Workshop” lessons as part of my Data Carpentry instructor training checkout procedure. 

1. I have proof-read the lesson materials and noticed the following typos in the code or in the text: 

http://www.datacarpentry.org/shell-genomics/lessons/01_the_filesystem.html:
- [x] "Let's go into the sample data directory: cd dc_sample data”  - the directory name should be “dc_sample_data"
- [x] “We can use a command line argument with 'ls' to get more information” 

- [x] "Another useful one is '-a', which show everything"

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/lessons/1.logging-onto-cloud.md: 
- [x] "Commercial clouds are can be very powerful”
- [ ] "We will cover as much as we you need to get through the Data Carpentry lessons”

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/lessons/4.parallel-analysis.md:
- [ ] "And you computer does each execution in order”
- [ ] "But what if you do'nt have enough cores to match the number of programs run?”
- [ ] "What commands can use you to see your process IDs?”

https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/00-readQC.md”
- [ ] "it will help your remember what you did”

https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/01-automating_a_workflow.md:
- [ ] "First, recall the code from our our fastqc workflow from this morning”

https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/02-variant-calling-workflow.md:
- [x] "so the name of each fastq file will by assigned to $fq"

2. At the lesson: https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/02-variant-calling-workflow.md 
mkdir command is repeated 5 times to create directories: 
$ mkdir -p results/sai
$ mkdir -p results/sam
$ mkdir -p results/bam
$ mkdir -p results/bcf
$ mkdir -p results/vcf
It could be done in one line instead: mkdir -p results/sai results/sam results/bam results/bcf results/vcf 

- [ ] 3. An additional exercise for https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/02-variant-calling-workflow.md lesson could be: “Explore the content of sam file and find the first 6 mandatory fields listed in SAM format specifications: https://samtools.github.io/hts-specs/SAMv1.pdf “

Please let me know if you need further clarification regarding my contributions and whether these would be sufficient for the checkout procedure.

Thank you
Asli Uyar

**Comment by ErinBecker** [comment]
@smcclatchy @aschuerch - since this issue was submitted a while back, I'm not sure how many of these typos and suggestions are still relevant. Could one of you or another maintainer please look through these and see what changes need to be made?

**Comment by aschuerch** [comment]
I checked off the typos that are not relevant anymore and posted issues to datacarpentry/cloud-genomics#18 and datacarpentry/wrangling-genomics/#39 and will close this issue with that.

**Comment by devbioinfoguy** [comment]
Thanks. I'll review these this afternoon!
