### ISSUE TITLE
Lesson contribution - Redirection

### ISSUE THREAD

**Issue by brunoasm** [datacarpentry/shell-genomics#284]
Hi,

Currently the objectives of **lesson 4: Redirection** list the following:

### Objectives
* Employ the grep command to search for information within files.
* Print the results of a command to a file.
* Construct command pipelines with two or more stages.

Each of these deserve a section in the lesson, but after the pipe section is over there are two very long sections on for loops, one of them specifically on `basename`

I see that for loops fit into the lesson subject by automating append redirect, but it seems to me that the objectives could include them as well to set the expectations in the beginning. Maybe the following objective could be added?

```
* Use for loops to run the same command for input several files.
```

**Comment by aschuerch** [comment]
Thank you @brunoasm for bringing this up, the objectives would certainly be more complete by including for loops. Are you up to submitting a PR to include this?
