### ISSUE TITLE
Lesson contribution – Removing potentially redundant content -  Instructor Checkout

### ISSUE THREAD

**Issue by jpaganini** [datacarpentry/shell-genomics#287]
#### Episode: Introducing the Shell

Hi Carpentries team,

I’m Julian, I’m doing my PhD at UMC Utrecht and I recently took a Carpentries Instructor Training. Awesome experience I must say, really enjoyed it. 

I would like to make a small suggestions for the episode of Introducing the Shell. I think there might be some redundancy on ‘Tab Completion’ section:

##### * In lines 312,315 and 316 students are indicated to change directories to `untrimmed_fastq`. But shortly after, starting from line 324, they'll have to repeat the same procedure (see below)

---
(*line 312*) Now change directories to `untrimmed_fastq` in `shell_data`

~~~
$ cd shell_data
$ cd untrimmed_fastq
~~~

Using tab complete can be very helpful. However, it will only autocomplete a file or directory name if you've typed enough characters to provide a unique identifier for the file or directory you are trying to access.

(*line 324*) If we navigate back to our `untrimmed_fastq` directory and try to access one of our sample files: 

~~~
$ cd
$ cd shell_data
$ cd untrimmed_fastq
$ ls SR<tab>
~~~
The shell auto-completes your command to `SRR09`, because all file names in the directory begin with this prefix. When you hit <kbd>Tab</kbd> again, the shell will list the possible choices.

---

##### * I think this might be confusing, since at that point, students are already working in the `untrimmed_fastq` directory. Therefore I suggest making a small re-arrangment of this section as follows:

---

(*line 312*) Now change directories to `untrimmed_fastq` in `shell_data`

~~~
$ cd shell_data
$ cd untrimmed_fastq
~~~

Using tab complete can be very helpful. However, it will only autocomplete a file or directory name if you've typed enough characters to provide a unique identifier for the file or directory you are trying to access.

(*new_line 324*)  For example, if we now try to list the files which names start with `SR` by using tab complete:

~~~
$ ls SR<tab>
~~~
The shell auto-completes your command to `SRR09`, because all file names in the directory begin with this prefix. When you hit <kbd>Tab</kbd> again, the shell will list the possible choices.

**Comment by akshayparopkari** [comment]
Thank you for your contribution, @jpaganini

I agree with your suggestion on removing redundancy. Additionally, it also enables a continuous flow during instruction. 

If @datacarpentry/shell-genomics-maintainers also agree, would you like to submit a PR with your change? For step-by-step guide on contributing to Carpentries lesson content, please refer to [instructions for Carpentries lesson contribution](https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md#instructions-for-contributing-to-the-carpentries-lesson-materials-using-graphical-or-command-line-interfaces-with-git-and-github).

**Comment by aschuerch** [comment]
Agreed @akshayparopkari , thank you for the suggestion @jpaganini ! A pull request would be greatly appreciated.

**Comment by jpaganini** [comment]
Hi @akshayparopkari and @aschuerch,

Thanks a lot for your prompt reply and feedback. I created a pull-request according to the instructions.

Cheers,
