### ISSUE TITLE
Error in wc -l output of "Redirecting output" section example ?

### ISSUE THREAD

**Issue by olisand** [datacarpentry/shell-genomics#289]
Please delete the text below before submitting your contribution. 

---

In the example given, grep is used to catch reads containing 10 Ns in the file SRR098026.fastq and wc -l is used to count the number of lines obtained. The number of lines shown for the output (537) is different from the one I get when doing it (802). Maybe the fastq file changed at some point and the text has not been adapted ? I know this is a very minor issue but I guess it could make some learners wonder why they don't get the same result.

---

**Comment by olisand** [comment]
I copied the data from Figshare to prepare a checkout lesson.

**Comment by akshayparopkari** [comment]
I am getting the same result as @olisand -

```{bash}
$ ls
SRR097977.fastq	SRR098026.fastq

$ grep -B1 -A2 NNNNNNNNNN SRR098026.fastq | wc   
     802    1338   24012
```

**Comment by akshayparopkari** [comment]
I suggest that we update the numbers in the lesson since most instructors as well as learners will be downloading the data from FigShare. What do you think, @datacarpentry/shell-genomics-maintainers?

**Comment by aschuerch** [comment]
Ideally, the data in FigShare should match the AWS instances. But I guess you are right @akshayparopkari that the data in FigShare should probably be leading. What's your opinion @datacarpentry/shell-genomics-maintainers ?

**Comment by akshayparopkari** [comment]
1. Are FigShare data files subject to changes?
A. If we accept FigShare as the right approach. Are the AWS instances updated when FigShare updates FASTQ files?

Instead of focusing on matching the `wc` values on the lesson page, there could be an emphasis on `wc` numbers driven by FASTQ data at the time of workshop. An option is to add a timestamp disclaimer on the `wc` commands. Something along the lines of -

> This command counts the number of words, lines, and characters in a file. The FASTQ file may change over time and as of Sept. 2020, `wc` gives the following output -

```
$ wc bad_reads.txt
     802    1338   24012
```

Thoughts, @datacarpentry/shell-genomics-maintainers ?

**Comment by esallychang** [comment]
Hi, I like this addition. I also propose adding something like "Given the potential for updates to the FASTQ files in this lesson, make sure your file matches your instructor's output." I will make a pull request ASAP adding the language proposed by @akshayparopkari and myself and close this issue out once that is done.

**Comment by esallychang** [comment]
Hi @datacarpentry/shell-genomics-maintainers I just need someone else to take a look at either suggest further edits or go ahead and merge my pull request+close the issue if looks good whenever you get a chance. Totally get that it is a holiday week so I'll check back next week if I haven't heard anything.

**Comment by akshayparopkari** [comment]
Lgtm, I'll wait a few more days before merging the changes to hear comments from other maintainers.
