### ISSUE TITLE
Reference for teaching the command line to biologists

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/shell-genomics#29]
This could be a useful reference in thinking about teaching or presenting the shell to people new to the command line

Addressing the digital divide in contemporary biology: Lessons from teaching UNIX
http://www.biorxiv.org/content/early/2017/04/07/122424.full.pdf+html

HT @ctb

**Comment by ErinBecker** [comment]
Closing this as it is referenced in another issue about references.

**Comment by ErinBecker** [comment]
Add this reference to the "Reference" extras page?
