### ISSUE TITLE
Typo and confusion in PSCP command

### ISSUE THREAD

**Issue by JesseKerkvliet** [datacarpentry/shell-genomics#297]
Link: https://datacarpentry.org/shell-genomics/05-writing-scripts/index.html

In the last part, when transferring files from the instance to a Windows machine, we saw confusion about the last command.

```{shell}
C:\User\your-pc-username\Downloads> pscp.exe dcuser@ec2-54-88-126-85.compute-1.amazonaws.com:/home/dcuser/shell_data/untrimmed_fastq/scripted_bad_reads.txt.
```

1. There seems to be missing a space between the path of scripted_bad_reads.txt and the target (.)
2. Partially because of this, we saw some confusion in our last workshop because it was unclear to some what the purpose of this '.' was. It might be helpful to specify that the . is the directory we want to move our file to.

**Comment by akshayparopkari** [comment]
Hi @JesseKerkvliet, thank you for sending in your comment! I agree with your proposed changes and would welcome a PR 👍 
For step-by-step guide on contributing to Carpentries lesson content, please go through [instructions for Carpentries lesson contribution](https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md#instructions-for-contributing-to-the-carpentries-lesson-materials-using-graphical-or-command-line-interfaces-with-git-and-github).
