### ISSUE TITLE
Lesson contribution - instructor checkout – Navigational shortcuts

### ISSUE THREAD

**Issue by Upe-ndra** [datacarpentry/shell-genomics#298]
Section: Navigational shortcuts [Link](https://datacarpentry.org/shell-genomics/02-the-filesystem/index.html)

Hi I am Upendra, a PhD candidate at University of Otago. I would like to suggest mentioning another navigational shortcut `cd -`  in this section. As this shortcut takes you back to your last location and is very handy for a quick navigation between two directories.

**Comment by akshayparopkari** [comment]
Hi @Upe-ndra, thank you for submitting your suggestion 👍

The lesson goes over the three most common bash navigational shortcuts for root, home and one level up directory. The lesson covers navigating within the data folder provided in the setup. Based on the lesson contents and exercises, adding the - shortcut could be abstract for the learners to fully grasp its utility. Furthermore, it might need addition of new content to help learners practice the shortcut - increasing the lesson teaching time. Having said that, I use the shortcut frequently and find it it quite useful.

What do you think, @datacarpentry/shell-genomics-maintainers?

**Comment by aschuerch** [comment]
Thank you @Upe-ndra for your contribution!  `cd -` is very useful!
However, I agree with @akshayparopkari and I often encounter confusion at workshops regarding `/`, `~`, and `..` characters. I would be reluctant to include any more in the lesson.

**Comment by esallychang** [comment]
Hi - thanks again to @Upe-ndra for this suggestion. However, I agree with my other maintainers that it would add new content that we simply do not have time for, seeing as these lessons usually already go a bit over time! If this is a shortcut that a particular instructor uses often, they are of course more than welcome to mention it if time is available, without us needing to add any extra "official" content. I am closing this issue out now.
