### ISSUE TITLE
Typo in solution in the Project Organization episode

### ISSUE THREAD

**Issue by dirostri** [datacarpentry/shell-genomics#305]
Greetings, 

I hope this is the right forum. I believe to have found a typo in the solution of the second exercise in Project Organization. In the exercise, the command is saving the last 8 lines of the history. However the explanation says it's the last seven. I think the discrepancy could cause confusion among beginners.

**Comment by akshayparopkari** [comment]
Thanks for your input, @dirostri!

I have initiated a pull request #306 to clarify the text.
