### ISSUE TITLE
03-working-with-files permission file images

### ISSUE THREAD

**Issue by NadineBestard** [datacarpentry/shell-genomics#308]
After explaining the permission files concept and showing how to use it to protect your files as #223 suggests, a student asks how would you change the other premissions. The conversation led to explain the chmod -ugo (user, group, others). There was then a lot of confuison due to the image used to explain the concept, labbeled with "owner, group, users". 
> "Is **"u"** other users or yourself?? Is not **"o"** from owner, like the image? "

I am not suggesting we should include these chmod commands if there are not asked by the students, but it would help having a better image in case they do.

**Comment by aschuerch** [comment]
Hi Nadine, Thank you very much for this useful feedback. Could you maybe make a suggestion what would be better? If you feel up to it, a pull request would be highly appreciated.

**Comment by NadineBestard** [comment]
I suggeted another image in the pull request #309

**Comment by p-j-smith** [comment]
lIt looks like this was fixed in #309 so I'll close this issue, but feel free to reopen if not
