### ISSUE TITLE
"it" is too imprecise in some cases

### ISSUE THREAD

**Issue by jsgro** [datacarpentry/shell-genomics#310]
I will comment on a specific short paragraph on Lesson 05 [Writing Scripts and Working with Data](https://datacarpentry.org/shell-genomics/05-writing-scripts/index.html) using the word "it": 

"*We had to type `bash` because we needed to tell the computer what program to use to run this script. Instead, we can turn this script into its own program. We need to tell it that it’s a program by making it executable.*"

The last phrase has 13 words and 3 "it". In the portion "*We need to tell it*" does "it" refer to the computer, or to the script?

"it" would likely refer to the last understandable item in a previous phrase. Preceding immediately is: "*we can turn this script into its own program.*"  From this one could conclude that "it" was referring to the script. In other words, by changing the permissions the script will "know" that it is a script. But I believe that this information is more relevant to be given to the computer, or at least the OS, for which the execute mark `x` makes sense. In that sense "it" would refer to the computer. Perhaps a better phrasing might be:

*We need to tell the computer that this script is a program by making the script file executable.*

This removes all 3 "it" from the phrase avoiding any doubts.

The lesson is fine and these "it" do not prevent for understanding what is happening.  
I just find that "it" is often imprecise, and replacing that word with a more relevant word may be beneficial for a better understanding of the text. There are 10 "it" in the 3 paragraphs under **Which Editor?** and a few of them would benefit from being replaced also. For example:

Original:   
When we say, "`nano` is a text editor," we really do mean “text”: it can only work with plain character data, 

Suggested: replace the "it" after the colon with a repetition of the word `nano` would make the text more clear:    
When we say, "`nano` is a text editor," we really do mean “text”: `nano` can only work with plain character data, 

Disclaimer/Apologies: I am a non-native English speaker, and it may be that this is why I find this unclear.

**Comment by aschuerch** [comment]
Hi @jsgro, many of our instructors and learners are non-native English speakers (as am I) - thank you for signalling that the wording here might be unclear. May I suggest opening a draft-pull request, where all of the @datacarpentry/shell-genomics-maintainers can weigh in on the wording? Given the different language backgrounds, I am sure we can together come up with a solution that improves upon the current version.

**Comment by akshayparopkari** [comment]
Thanks for your comment, @jsgro. I agree with @aschuerch, your suggestion provides an improved way of approaching this section. Your alternative structuring below looks like a good fit to me. @jsgro, please feel free to open a draft PR. 

> We need to tell the computer that this script is a program by making the script file executable.

**Comment by jsgro** [comment]
Thank you @aschuerch and @akshayparopkari for your positive feedback. I have created a pull-request. Indeed this is my very first pull-request!
