### ISSUE TITLE
Lesson contribution - instructor checkout - Working with files and directories

### ISSUE THREAD

**Issue by Elahep** [datacarpentry/shell-genomics#319]
In the "Command History" section where some useful shortcuts are introduced, I think it can be helpful to add a sentence explaining what the Ctrl+R shortcut does. For example, it can be mentioned that:

Ctrl+R will do a reverse search through your command history. When using this shortcut, start typing your command, it will show you the most recent matching command previously typed in the shell.

**Comment by p-j-smith** [comment]
He @Elahep, sorry for the slow reply and thanks for the suggestion! I think it is a good idea to give a little more explanation on how to use Ctrl+R, perhaps:

> Ctrl+R will do a reverse search through your command history. Press Ctrl+R then start typing a search string - the most recent command that contains your search string will be displayed. Press `enter` to execute it.
