### ISSUE TITLE
Amazon AMI for this lesson?

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#37]
I was just proofreading this lesson for the issue bonanza, and was unable to test the commands "for real" because I don't have access to the EC2 instance learners would have. Luckily, this is pretty data-agnostic stuff, so no complaints, but it got me wondering if there was an Amazon AMI for this lesson so that solo learners or non-official workshop runners can follow along? I found this blog post[http://www.datacarpentry.org/blog/amsterdam-genomics/](http://www.datacarpentry.org/blog/amsterdam-genomics/) referencing such an AMI, but did not find it in the Amazon AMI marketplace. Can we consider making it part of lesson materials?

**Comment by standage** [comment]
+1. This is definitely in the spirit of the rest of the Software/Data Carpentry materials.

**Comment by JasonJWilliamsNY** [comment]
Yes there is an AMI: ami-aab445c7

**Comment by mfoos** [comment]
Found it, thanks Jason - wasn't looking in the right place :)

**Comment by ErinBecker** [comment]
Thanks @JasonJWilliamsNY - is this in the materials somewhere? If not, can we put it somewhere? I had the same issue myself when preparing to teach for the first time. I didn't know there was an AMI and didn't see any mention of it anywhere. Maybe this should go in the instructor notes?

**Comment by JasonJWilliamsNY** [comment]
@ErinBecker - Yes, this should be in instructor notes. Right now Maneesha sets things up. We will have multiple ways to run this, so we will need a place to describe those instructions.

**Comment by ErinBecker** [comment]
The AMI is currently described on the  [workshop overview page](http://www.datacarpentry.org/genomics-workshop/). We should add a link to the instructor notes and/or prerequisites for this lesson.
