### ISSUE TITLE
Missing "structural" elements

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#38]
Overall:
- [x] Setup (known issue, included for completeness)
- [x] Instructor Notes (known issue, included for completeness)
- [ ] Extras>Glossary is blank
- [x] Extras>About only shows LC/SWC/DC generic "about" info 
- [x] Extras>Figures & Extras>Discussion are blank

[http://www.datacarpentry.org/shell-genomics/01-introduction/](http://www.datacarpentry.org/shell-genomics/01-introduction/)
* Fine

[http://www.datacarpentry.org/shell-genomics/02-the-filesystem/](http://www.datacarpentry.org/shell-genomics/02-the-filesystem/)
- [x] Time estimates missing
- [x] Typo/fragment in Questions
- [x] No key points

[http://www.datacarpentry.org/shell-genomics/03-working-with-files/](http://www.datacarpentry.org/shell-genomics/03-working-with-files/)
- [x] Time estimates missing
- [x] Questions missing
- [x] No key points
- [x] answer to "bonus" wildcard question missing

[http://www.datacarpentry.org/shell-genomics/04-redirection/](http://www.datacarpentry.org/shell-genomics/04-redirection/)
- [x] Time estimates missing
- [x] Questions missing
- [x] No key points
- [x] Exercises lack solutions

[http://www.datacarpentry.org/shell-genomics/05-writing-scripts/](http://www.datacarpentry.org/shell-genomics/05-writing-scripts/)
- [x] Time estimates missing
- [x] Existing Question needs question mark

[http://www.datacarpentry.org/shell-genomics/XX-organization/](http://www.datacarpentry.org/shell-genomics/XX-organization/)
- [x] Time estimates missing
- [x] Questions missing
- [x] Objectives missing
- [x] No key points

**Comment by standage** [comment]
Perhaps we should change these from bullets to check boxes and tick them as we go?

**Comment by aschuerch** [comment]
I updated the issue with the check boxes. See also #36

**Comment by smcclatchy** [comment]
Thanks, @mfoos for compiling this checklist. I have cross-referenced this in our [list of issues](https://github.com/datacarpentry/shell-genomics/issues/36).

**Comment by ErinBecker** [comment]
This is great! Thanks @mfoos for putting this together. I'm checking off the "About" extra, as that's actually the information that is intended to be on that page.

**Comment by ErinBecker** [comment]
On a related note, other lessons have gotten rid of the "Figures" extra due to problems keeping that file in synch with additions and deletions of figures from the lessons. 

Examples of lessons that have gotten rid of "Figures" are:
http://www.datacarpentry.org/spreadsheet-ecology-lesson/
and 
http://swcarpentry.github.io/instructor-training/

**Comment by ErinBecker** [comment]
Extras>Discussion has historically been used for old modules that are no longer included in the regularly scheduled workshop. If there are none of those for this lesson, that file can also be removed.

**Comment by psorianom** [comment]
Hey!  I believe that the item  "Existing Question needs question mark" has been solved so I guess it should be checked ?

**Comment by aschuerch** [comment]
Thanks @psorianom, well spotted!

**Comment by ErinBecker** [comment]
Moving the one remaining issue to a separate issue and closing.
