### ISSUE TITLE
provide starting working directory for exercise (filesystem episode)

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#40]
There's an exercise where the challenge is 
> There is a hidden directory in our file system. Explore the options for ls to find out how to see hidden directories. List the contents of the directory and identify the name of the text file in that directory.

but it occurs immediately after a section about learning how to navigate between directories, so adventurous learners may not be in the right directory when this challenge arises. Adding the starting directory to the question would help learners get the intended takeaway.

**Comment by swang8** [comment]
Good suggestion.
