### ISSUE TITLE
Confusing wording "the home directory" (filesystem episode)

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#41]
> Navigate to the home directory if you are not already there.

Intention is to get learner to THEIR home directory, but if you're not used to the concept of your home directory, this could come across as "the directory called home". Proposing change to 

> Navigate to your home directory if you are not already there.

**Comment by swang8** [comment]
Sounds good.
> Navigate to your `HOME` directory if you are not already there.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/78
