### ISSUE TITLE
Formatting issues in Redirection & Writing Scripts episodes

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#42]
1. Exercises/challenges not formatted with colored boxes
2. When append (>>) is introduced, the characters are oddly formatted (redirection only)
3. Use of inline "as-code" formatting for unix commands (cut, sort, uniq, etc.) & directory names disappears as you go further down the page (redirection) or is spotty (writing scripts)
4. Code examples not block-quoted (bottom of writing scripts)

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/78
