### ISSUE TITLE
typos in redirection episode

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#43]
1. "grep" misspelled as "greap"
2. In the second "sort" example there is extra whitespace

**Comment by smcclatchy** [comment]
Eagle eyes!

**Comment by ErinBecker** [comment]
@smcclatchy it looks like you fixed this in your fork. Could you please put in a PR and then I think we can close this! :-)

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/shell-genomics/pull/78
