### ISSUE TITLE
Episode 6 appears somewhat out of order

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#44]
I think this could be fixed by removing
> In this exercise we will setup a filesystem for the project we will be working on during this workshop. We will also introduce you to some more helpful shell commands, programs and tools, including:
mkdir
history
tail
|
nano

and

> We will talk much more about the | command in a later lesson. For now, it’s important to know that this is called a pipe and it sends the output of the first command (history) as input to the next command (tail). We have used the -n option to give the last 7 lines of our history.

and perhaps also the "Questions" at the bottom, which don't seem too connected

**Comment by swang8** [comment]
Questions seem more suitable for episode "redirection"..
