### ISSUE TITLE
Permissions discussion incomplete (writing scripts)

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/shell-genomics#45]
> We see that it says “-rw-r–r–” which means that the file can mainly be read. That’s the ‘r’.

I don't think this is a complete enough explanation, my argument being that it doesn't meet the standard of giving learners a starting place to learn the finer points themselves. I know this borders on "adding a concept" but maybe we can brainstorm something?

**Comment by JasonJWilliamsNY** [comment]
I taught this yesterday and finally felt the need to introduce (with a figure) just enough info on permissions that folks could understand the chmod +x. This was also a good time for me to introduce adding a program to PATH.

**Comment by standage** [comment]
We also gave a crash course in file permissions and the path variable for the March workshop at CSUMB. We weren't able to make it through the workshop without fiddling with the software configuration environment.
