### ISSUE TITLE
Should be no setup. 

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/shell-genomics#48]
No setup info specific to this lesson as its on the cloud. Also, the Shell lesson starts assuming folks are on a local machine; should be scrubbed.

**Comment by aschuerch** [comment]
Having no setup info will make it hard for self-directed learners to follow the lesson. Especially the shell-genomics lesson is doable on a local computer. See also the discussion at datacarpentry/wrangling-genomics#27 and datacarpentry/organization-genomics#30

**Comment by JasonJWilliamsNY** [comment]
This is a bigger overall question for the genomics lessons, and also for the Shell lesson maintainers. The original intention (in my understanding) is that these lessons weren't conceived to be run locally (even if many/any of them could be). They were always meant to be cloud-based, with self-directed learners working on their own cloud instance. I am not against things being able to run locally, but this issue probably affects every lesson and so we should be consistent either in providing one option, or multiple options.

**Comment by aschuerch** [comment]
Agreed. Something to be discussed in the advisory committee @tracykteal

**Comment by tracykteal** [comment]
Agree. We should discuss this in the advisory committee meeting. I'll get out a scheduling email for that meeting.

**Comment by tracykteal** [comment]
I created an issue in genomics-workshop about this and gave it an AdvisoryCommittee label. https://github.com/datacarpentry/genomics-workshop/issues/27

**Comment by ErinBecker** [comment]
Creating a meta-issue in genomics-workshop to hold all set-up related issues for these lessons. See link above.
