### ISSUE TITLE
Use containers for configuring software environment?

### ISSUE THREAD

**Issue by standage** [datacarpentry/shell-genomics#49]
For the most part, beginner practitioners of genomics don't *really* need to worry about whether their terminal is connected to their laptop, a cluster on campus, Jetstream, AWS, or something else. (Of course, they need to know that some computers have more resources than others, so sometimes we connect a remote computer instead of our laptop/desktop for big jobs.) But for beginners I don't think the distinctions between laptop, cloud, HPC, etc, are all that meaningful.

Perhaps one of the challenges is having a unified software installation across all of these platforms? If so, I'd suggest we create a single unified Docker container with all of the prerequisite software installed, and use this to teach the shell independent of the hardware we're using for the back end. AWS machines can run Docker images, Jetstream machines can run Docker images, and anyone with root access to their laptop or desktop can run Docker images. The biggest potential issue is HPC provisioning, since most sysadmins are reluctant to install Docker (requires privilege escalation). But Singularity is a compatible alternative (should run Docker images fine) that does not require privilege escalation.

I'd be happy to spearhead the effort to create the official "Data Carpentry shell genomics" Docker image if there is support for this idea.

**Comment by aschuerch** [comment]
Thank you @standage and sorry for the delay in addressing this issue.  I think a Docker image would provide flexibility from the current approach and would be a good way to be able to set up the workshop on a different infrastructure. Therefore your suggestion concerns the whole genomics-workshop and not only the shell lesson, and I took the liberty to open an issue at datacarpentry/genomics-workshop#28

**Comment by swang8** [comment]
@standage I think it's great to have a Docker image. I went through the contents of shell-genomics, did't seem to see any specific software/tools are required. So for this particular lesson, Docker image is not urgent to have; but for other lessons that require specific tools, Docker image is very useful.

**Comment by standage** [comment]
For sure. Some of the genomics materials are organized by topic, and I think this is great. Some of the materials are organized by hardware. Something like Docker should make this latter distinction unnecessary, and would presumably reduce the burden for all involved in teaching workshops and maintaining materials.

**Comment by aschuerch** [comment]
As we seem to agree that this should be taken up for the workshop as a whole (datacarpentry/genomics-workshop#28) I will close this issue here. Thank you @standage for bringing this up.
