### ISSUE TITLE
Waiting to introduce navigating two directories at once

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/shell-genomics#50]
In 01-introduction the concept of navigating two directories at once, "cd dc_sample_data/untrimmed_fastq" is introduced. This is actually a difficult concept, so it's likely best to wait to introduce it until later in the lesson.

**Comment by tracykteal** [comment]
Could move this section to 02-the-filesystem where there's the ls ../.. command

**Comment by aschuerch** [comment]
At this point this is included in the 02-the-filesystem (first chaining together with ls ../../ and then transferring the concept to cd dc_sample_data/untrimmed_fastq) and can thus safely be removed in 01-introduction
