### ISSUE TITLE
`/` is the root directory

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#59]
03-working-with-files.md gives an example and an exercise using wildcards to search files in `/usr/bin`.  It's not immediately clear, however, to those not familiar with the filesystem that the leading `/` in `/usr/bin` corresponds to the root (top level) directory and that this command will work regardless of the user's current location in the filesystem. Need to add this to the "Navigational shortcuts" section in the previous episode.

**Comment by smcclatchy** [comment]
The previous episode, The Filesystem , contains a Navigation shortcuts section that is confusing. The final paragraph in this episode says:
"To summarize, while you are in the `shell` directory, the commands ls ~, ls ~/., ls ../../, and ls /home/dcuser all do exactly the same thing."
I don't believe there is a `shell` directory, and I'm not sure that `ls ../../` will do the same things as the other command arguments will.
This should probably be addressed at the same time that `/usr/bin` is addressed.

**Comment by aschuerch** [comment]
At this point, an explanation of ` / `  is included in 02-the-filesystem under the header Full vs. Relative Paths. 

The sentence at the end of 02-the-filesystem starting with "To summarize" however is very confusing.

**Comment by ErinBecker** [comment]
There is indeed no `shell` directory. 

(Confirmed using `ls ~  -R | grep "shell"`). 

And `ls ../../` definitely doesn't give the same output as the other three. I'm working on a revision to this language and will put in a PR soon.
