### ISSUE TITLE
Difficult to keep commands up to date with changes in top level directory name

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/shell-genomics#6]
An issue is that we often change the name of the main directory that files are downloaded to. This then means that the commands that people need to write change, and then either all the commands have to be updated, or they just don't match what we're typing.

One thing that might help is to define the 'directory' in the YAML header then just use {{ page.directory }} in the commands. Although I'm not sure if the YAML will render within code blocks.

**Comment by ErinBecker** [comment]
I've taught this lesson twice recently and also run through the full lesson on my own a few times and didn't run into this issue. I'm assuming it has been fixed sometime in the past two years. Closing issue but @tracykteal please let me know if you would like to reopen.
