### ISSUE TITLE
"cat" is a confusing example for text searching

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#62]
In 03-working-with-files, section on examining files - 

> Note, if you are at the end of the file and search for the word “cat”, less will not find it. You need to go to the beginning of the file and search.

I know that "cat" is being used because it's a three letter string that will occur in a nucleotide file, but it's confusing because `cat` is also a command that was discussed just recently. Change to another string, like "caa", to avoid confusion.

**Comment by swang8** [comment]
This
