### ISSUE TITLE
add loops episode

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/shell-genomics#67]
When I taught this lesson with @k8hertweck last month, we finished the shell lessons early and ended up improvising an episode on loops. Introducing loops on the first day was very useful for the learners and they used that skill several times on day 2 (I'm not sure whether it is part of the normal day 2 curriculum to do loops or if that was something Kate added). 

I propose introducing an episode on loops between 03-working-with-files and 04-redirection.

A very useful for loop at this point in the lesson would be: 
`for FILENAME in *; do mv $FILENAME $FILENAME-copy; done`
to allow learners to rename all of the backup files they created in the previous episode. 

This also allows for more challenging exercises including:
- a for loop including changing file permissions in batch to change backup files to read-only
- a for loop including creating of the backup copies, in addition to renaming them

**Comment by swang8** [comment]
Can this be added as part of 03-working-with-files, unless the plan is to have a new episode?

**Comment by basmith89** [comment]
Maybe this could come after the 05-writing-scripts episode as well?  If placed there a question of script automation on say an entire directory could be used as well compounding the utility of script building and for loops.

**Comment by ErinBecker** [comment]
I propose holding off on this change until after lesson release so that we can have a thorough discussion and not rush implementation.

**Comment by ErinBecker** [comment]
Now that I'm more familiar with the curriculum, I see that we do cover loops in the wrangling lesson (http://www.datacarpentry.org/wrangling-genomics/03-automation/) so I'll close this issue.
