### ISSUE TITLE
issue list 04-redirection

### ISSUE THREAD

**Issue by swang8** [datacarpentry/shell-genomics#95]
Overview
- [x] Missing key questions
- [x] Missing time estimation

Content
- [x] " `>>` will append new output to the end of a file, rather than overwriting it. ",   `>>` was called "append redirect" in episode 06, give it a name here?
- [x] Add one exercise as noted by #35
- [x] Need one more exercise for using `grep`: i.e., count the number of reads in `SRR097977.fastq` starting with `GAAAG` or `GAAAT` restriction enzyme cutting sites , `grep "^GAAA[GT]" SRR097977.fastq |wc -l `
- [x] key points missing
-  [x] Include callout (for instructor) about why we put the bad reads into a txt file instead of a fastq file (this should be included the first time this happens in the lesson.
- [x] "Bad reads have a lot of N's" --> make sure that we explain what an "N" represents somewhere. The first time this convention is used. 
- [x] Acknowledge that the cutoff of 10 Ns in a row is arbitrary. Doesn't mean that reads with 9 Ns in a row are good.

**Comment by ErinBecker** [comment]
@swang8 - I added a few things I noticed when I was going through my episode (05-writing-scripts) that I don't think we explained the first time they happened (04-redirection). Hope you don't mind that I added them directly to your list.

**Comment by ErinBecker** [comment]
See comments to #35 about the problems with adding the requested exercise.

**Comment by ErinBecker** [comment]
@swang8 - I like your suggested exercise for searching for sequences starting with restriction enzyme cutting sites. However, this does introduce two new concepts (regular expressions and metacharacters) that could potentially lead us down a rabbit hole. We do say earlier in the episode that we're not planning on teaching regular expressions, so I'm hesitant to introduce them here. 

What about introducing the use of a wild card within the `grep` search string? They're already familiar with wild cards and the use of the `*` as a wild card specifically, so even though this technically turns the search string into a regular expression, I think it would be lower cognitive load than introducing the `^` metacharacter or `[]` based options. What do others think?

**Comment by swang8** [comment]
I realize that `^`, `$` and `[]` have not been introduced in the episode.. Might be confusing for students.. @ErinBecker

**Comment by ErinBecker** [comment]
@swang8 - I'd love to have a whole lesson (or at least an episode) on regex at some point (as it's really, really useful in a lot of workflows), but unfortunately I don't think it fits into these materials.
