### ISSUE TITLE
Add an awk episode

### ISSUE THREAD

**Issue by basmith89** [datacarpentry/shell-genomics#97]
A brief lesson on awk could have big payoffs.  Perhaps this could be placed in another lesson as well (ecology lessons could be a good fit), but I find awk very useful when extracting data from csv/tsv files for reformatting or data extraction.  Further, it is a useful tool in general when using the command line.  I understand that it might be a bit into the command line weeds, but maybe a general introduction to awk could be beneficial.

An example could be retrieving data from specific columns of a BLAST output file that had identify matches greater than 70%:

`awk '{OFS="\t"; if($3>70)print$1,$2,$3,$5}' blast_output >blast_output_edited`

This shows the power of awk and relates it to a biological context for the genomics workshop.

**Comment by aschuerch** [comment]
Thank you @basmith89 for raising this. I agree that awk is indeed a very useful, very powerful tool! However there are quite a number of new concepts involved in this single line of awk which would not fit in a brief lesson imho and which would mean we would have to omit other content. What do you think @ErinBecker @smcclatchy?

**Comment by ErinBecker** [comment]
Agreed that `awk` is very useful and will make a good addition to the learner's knowledge base. However, as @aschuerch mentioned, the single line of code you cited introduces quite a number of new concepts and will not fit into the lessons as currently written. I recommend holding off on this until/if we create an intermediate version of these lessons.
